# Generated by Django 3.2.6 on 2022-04-19 05:20

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxAbbreviations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)])),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(max_length=20, unique=True)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('filer_user', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('temporality', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_abbreviation', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OriginBoxSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='PublicWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('unity_abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('administrative_bond', models.CharField(blank=True, max_length=100, null=True)),
                ('bond_abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archives_app.document')),
                ('received_date', models.DateField()),
            ],
            bases=('archives_app.document',),
        ),
        migrations.CreateModel(
            name='OriginBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('subject', models.ManyToManyField(to='archives_app.OriginBoxSubject')),
            ],
        ),
        migrations.CreateModel(
            name='FrequencySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('role', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('municipal_area', models.CharField(max_length=100)),
                ('reference_period', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('process_number', models.CharField(blank=True, max_length=20, null=True)),
                ('temporality_date', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('document_name_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.documentname')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.publicworker')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives_app.unity')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('month', models.CharField(blank=True, max_length=3, null=True)),
                ('temporality_date', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('document_name_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives_app.documentname')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='sender_unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives_app.unity'),
        ),
        migrations.CreateModel(
            name='AdministrativeProcess',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archives_app.document')),
                ('notice_date', models.DateField()),
                ('interested', models.CharField(max_length=150)),
                ('reference_month_year', models.DateField(blank=True, null=True)),
                ('archiving_date', models.DateField(blank=True, null=True)),
                ('is_filed', models.BooleanField(blank=True, null=True)),
                ('is_eliminated', models.BooleanField(blank=True, null=True)),
                ('send_date', models.DateField(blank=True, null=True)),
                ('administrative_process_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('temporality_date', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('document_name_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.documentname')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.publicworker')),
                ('unity_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unfiled_unity', to='archives_app.unity')),
            ],
            bases=('archives_app.document',),
        ),
        migrations.CreateModel(
            name='FrequencyRelation',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archives_app.relation')),
                ('reference_period', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), size=None)),
                ('temporality_date', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('sender_cpf', models.CharField(max_length=11)),
                ('receiver_cpf', models.CharField(max_length=11)),
                ('document_name_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.documentname')),
                ('receiver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver_publicworker', to='archives_app.publicworker')),
                ('sender_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender_publicworker', to='archives_app.publicworker')),
            ],
            bases=('archives_app.relation',),
        ),
        migrations.CreateModel(
            name='BoxArchiving',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archives_app.relation')),
                ('document_url', models.URLField(blank=True, null=True)),
                ('cover_sheet', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.boxabbreviations')),
                ('document_names', models.ManyToManyField(to='archives_app.DocumentNames')),
                ('origin_box_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.originbox')),
                ('rack_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.rack')),
                ('shelf_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.shelf')),
            ],
            bases=('archives_app.relation',),
        ),
    ]
