# Generated by Django 3.2.6 on 2022-04-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyrelation',
            name='receiver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver_publicworker', to='archives_app.publicworker'),
        ),
        migrations.AlterField(
            model_name='frequencyrelation',
            name='sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender_publicworker', to='archives_app.publicworker'),
        ),
    ]
