# Generated by Django 3.2.6 on 2022-04-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeprocess',
            name='administrative_process_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
