# Generated by Django 3.2.6 on 2022-04-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxarchiving',
            name='abbreviation_id',
        ),
    ]
