# Generated by Django 3.2.6 on 2022-04-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxarchiving',
            name='unity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unfiled_box_unity', to='archives_app.unity'),
        ),
    ]
