# Generated by Django 3.2.6 on 2022-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentname',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
