# Generated by Django 3.2.6 on 2022-04-03 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeprocess',
            name='administrative_process_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='boxabbreviations',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='process_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='documentname',
            name='document_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filelocation',
            name='file',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publicworker',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='unity',
            name='unity_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
