# Generated by Django 3.2.6 on 2022-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxabbreviations',
            name='number',
        ),
        migrations.RemoveField(
            model_name='boxabbreviations',
            name='year',
        ),
        migrations.AlterField(
            model_name='publicworker',
            name='cpf',
            field=models.CharField(max_length=16),
        ),
    ]
