# Generated by Django 3.2.6 on 2022-04-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0002_auto_20220404_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativeprocess',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='administrativeprocess',
            name='dest_unity_id',
        ),
    ]
