# Generated by Django 3.2.6 on 2022-04-11 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0002_remove_boxarchiving_abbreviation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxarchiving',
            name='origin_box_id',
        ),
        migrations.RemoveField(
            model_name='originboxsubject',
            name='name',
        ),
        migrations.AddField(
            model_name='boxarchiving',
            name='origin_boxes',
            field=models.ManyToManyField(to='archives_app.OriginBox'),
        ),
        migrations.AddField(
            model_name='originboxsubject',
            name='document_name_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.documentname'),
        ),
    ]
