# Generated by Django 3.2.6 on 2022-04-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0003_auto_20220406_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeprocess',
            name='document_name_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.documentname'),
        ),
    ]
