# Generated by Django 3.2.6 on 2022-04-09 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0004_administrativeprocess_document_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeprocess',
            name='file_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.filelocation'),
        ),
        migrations.AddField(
            model_name='administrativeprocess',
            name='rack_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.rack'),
        ),
        migrations.AddField(
            model_name='administrativeprocess',
            name='shelf_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.shelf'),
        ),
    ]
