# Generated by Django 3.2.6 on 2022-04-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0004_administrativeprocess_document_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativeprocess',
            name='is_eliminated',
        ),
        migrations.RemoveField(
            model_name='administrativeprocess',
            name='is_filed',
        ),
        migrations.RemoveField(
            model_name='administrativeprocess',
            name='send_date',
        ),
        migrations.RemoveField(
            model_name='administrativeprocess',
            name='unity_id',
        ),
        migrations.AddField(
            model_name='boxarchiving',
            name='box_process_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_eliminated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_filed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='send_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='unity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unfiled_unity', to='archives_app.unity'),
        ),
    ]
