# Generated by Django 3.2.6 on 2022-04-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0005_auto_20220409_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeprocess',
            name='box_abbreviation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.boxabbreviations'),
        ),
    ]
