# Generated by Django 3.2.6 on 2022-04-12 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0006_administrativeprocess_box_abbreviation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeprocess',
            name='box_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrativeprocess',
            name='box_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
