# Generated by Django 3.2.6 on 2022-04-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0006_alter_boxarchiving_unity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxarchiving',
            old_name='unity_id',
            new_name='box_unity_id',
        ),
    ]
