# Generated by Django 3.2.6 on 2022-04-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0007_auto_20220412_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeprocess',
            name='box_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
